# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# making sure gcc is 4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
# Build steps
install:
  - if [ "`echo $CXX`" == "g++" ]; then export CXX=g++-4.8; fi
script:
  - mkdir build
  - cd build
  - cmake .. && make

